Add agent
vvv9912/GophKeeper pull request #1
Opened 2024-06-09 20:01 UTC by vvv9912

Первая версия агента и сервера

2024-06-09 20:01 UTC, vvv9912 commented
Планы:
1. Обработка ошибок от сервера
2. Конфиг
3. Шифрование файла
4. Удаление файлов при обновлении, при неудачном добавлении в бд
5. Функцию удаления из бд
6. Добавления обычного текста

2024-06-11 20:04 UTC, tmvrus requested changes
- пакет fmt для логирвание не предназначен, спринта примерно с 3го
- файлы по 500 строк это перебор, рекомендую их как-то разбить
- функции по 150 строк это тож перебор
- транзакции имеют смысл если в них больше одного запроса
- закоменченный код усложняет чтение

2024-06-11 20:04 UTC, tmvrus commented on cmd/Agent/main.go
> +	//создаём шаблон сертификата
если это нужно. то надо раскоментить, если нет - удалить

2024-06-11 20:04 UTC, tmvrus commented on cmd/Agent/main.go
> +	//	fmt.Println("Ошибка при создании файла сертификата:", err)
fmt для логирования не преднаначен

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/app/app.go
> +		return
return после паники не имеет смысла, управление до return не дойдет
использовать панику тоже не стоит, выше она нигде не перехватывается, если нужно аварийно завершить программу с ошибкой, есть хороший способ log.Fatal

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/auth.go
> +		fmt.Println(err)
?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/auth.go
> +			if len(Login) > 20 || len(Login) < 5 {
смысл цифр 20 и 5 ясен только автору кода

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/data.go
> +	time.Sleep(1 * time.Second)
?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/data.go
> +				val, ok := <-ch
а кто пишет в канал?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/data.go
> +				val, ok := <-ch
лучше читать в цикле, for val range := ch тогда цикл сам завершится когда канал закроют

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/data.go
> +	}
тут видимо должен быть return

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/command/data.go
> +		fmt.Println(err)
и тут

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/data.go
> +func (a *AgentServer) PostCrateFileStartChunks(ctx context.Context, data []byte, fileName string, uuidChunk string, nStart int, nEnd int, maxSize int, reqData []byte) (string, *RespData, error) {
первый раз вижу ф-ю с 8 аргументами!

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/data.go
> +	sizeChunk := 1024 * 1024
а почему не константа?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/data.go
> +		"Authorization": "Bearer " + a.JWTToken,
это 10 дублируется в проекте

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/data.go
> +		}
вот этот кусок примерно 15 раз встречается в коде, может сделать хелпер?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/data.go
> +	}
а это 8 раз встречается

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/server/server.go
> +)
а чего не константы

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/service/data.go
> +	path2 "path"
?

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/service/data.go
> +func (s *Service) UpdateBinaryFile(ctx context.Context, path string, userDataId int64, ch chan<- string) error {
передавать канал для записи внутрь ф-и это не очень идея, поскольку писатель не контролирует жизненный цикл или емкость канала, обычно "писатели" при запуске возвращают наружу канал из которого можно читать то что они пишут

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/service/data.go
> +// copyFile - копирование файла по новому пути и новым именим
не до конца понимаю зачем происходит копирование, но возможно os.Link будет проще

2024-06-11 20:04 UTC, tmvrus commented on internal/Agent/service/service.go
> +type AgentService interface{}
зачем?

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/app/app.go
> +	db, err := sqlx.Open("pgx", "postgres://postgres:postgres@localhost:5434/postgres?sslmode=disable")
все таки это должен быть конфиг

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/handler/auth.go
> +		return
жалько пользователя, он не узнает что случилось

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/handler/auth.go
> +		w.WriteHeader(http.StatusBadRequest)
потерянный return

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/service/filesaver.go
> +	defer file.Close()
если будет ошибка, то этот вызов повлечет панику, потому что file будет nil

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/service/filesaver.go
> +	defer file.Close()
тож самое

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/service/filesaver.go
> +func (s *SaveFiles) RunCronDeleteFiles(ctx context.Context) error {
ф-я никогда не возвращает ошибку

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/service/filesaver.go
> +	if fileInfo.Size() > 52_428_800 {
а почему столько?

2024-06-11 20:04 UTC, tmvrus commented on internal/Server/service/server.go
> +	return &Server{}
?

2024-06-11 20:04 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +	q2 := `SELECT meta_data FROM data WHERE  data_id = $1 `
а почему нельзя было сделать join?

2024-06-11 20:04 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +	tx, err := db.db.Begin()
а зачем запрос на чтение оборачивать в транзакцию?

2024-06-11 20:04 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +		if err == sql.ErrNoRows {
errors.Is примерно с 3го спринта

2024-06-11 20:04 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +	}()
7 раз в коде дублируется

2024-06-11 20:04 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +var (
а чо не константы?

2024-06-13 17:05 UTC, vvv9912 commented on pkg/store/postgresql/data.go
> +	tx, err := db.db.Begin()
Только для переиспользования функции, которая принимает на вход транзакцию

2024-06-14 07:46 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +	tx, err := db.db.Begin()
тогда объясни чего ты хочешь добавиться запуская запросы на чтение внутри транзакции?

2024-06-20 18:37 UTC, vvv9912 commented on pkg/store/postgresql/data.go
> +	tx, err := db.db.Begin()
Внутри этой функции GetData есть еще две функции. Одна из функций принимает транзакцию ( тк где-то в другой логике от этого запроса зависит выполнение всей операции) и я хочу как раз эту функцию и переиспользовать

2024-06-20 18:57 UTC, vvv9912 commented
Итоговая версия (тесты сделаю)

2024-06-20 20:10 UTC, tmvrus commented
тесты что-то жалуются на жизнь
```
go test ./... -cover
# GophKeeper/internal/Agent/Encrypt [GophKeeper/internal/Agent/Encrypt.test]
internal/Agent/Encrypt/encrypt_test.go:12:10: assignment mismatch: 1 variable but NewEncrypt returns 2 values
# GophKeeper/internal/Agent/server
internal/Agent/server/server.go:42:3: log.Panicln call has possible Printf formatting directive %s
	GophKeeper/cmd/Agent		coverage: 0.0% of statements
FAIL	GophKeeper/internal/Agent/Encrypt [build failed]
?   	GophKeeper/internal/Agent/model	[no test files]
FAIL	GophKeeper/internal/Agent/server [build failed]
	GophKeeper/cmd/Server		coverage: 0.0% of statements
	GophKeeper/internal/Agent/app		coverage: 0.0% of statements
	GophKeeper/internal/Agent/config		coverage: 0.0% of statements
	GophKeeper/internal/Agent/command		coverage: 0.0% of statements
	GophKeeper/internal/Agent/service		coverage: 0.0% of statements
	GophKeeper/internal/Server/app		coverage: 0.0% of statements
	GophKeeper/internal/Server/config		coverage: 0.0% of statements
	GophKeeper/internal/Server/authorization		coverage: 0.0% of statements
# GophKeeper/internal/Server/handler [GophKeeper/internal/Server/handler.test]
internal/Server/handler/auth_test.go:16:2: tests declared and not used
internal/Server/handler/auth_test.go:23:15: cannot use func(s *mock_service.MockAuth, ctx context.Context, login, password string) {…} (value of type func(s *mock_service.MockAuth, ctx context.Context, login string, password string)) as mockFunc value in struct literal
internal/Server/handler/auth_test.go:24:17: s.EXPECT().SignUp undefined (type *mock_service.MockAuthMockRecorder has no field or method SignUp)
internal/Server/handler/auth_test.go:31:15: cannot use func(s *mock_service.MockAuth, ctx context.Context, login, password string) {…} (value of type func(s *mock_service.MockAuth, ctx context.Context, login string, password string)) as mockFunc value in struct literal
internal/Server/handler/auth_test.go:32:17: s.EXPECT().SignUp undefined (type *mock_service.MockAuthMockRecorder has no field or method SignUp)
internal/Server/handler/auth_test.go:32:53: undefined: errors
FAIL	GophKeeper/internal/Server/handler [build failed]
?   	GophKeeper/pkg/fileUtils	[no test files]
	GophKeeper/internal/Server/middleware		coverage: 0.0% of statements
	GophKeeper/pkg/ShaHash		coverage: 0.0% of statements
	GophKeeper/internal/Server/service		coverage: 0.0% of statements
	GophKeeper/internal/Server/service/mocks		coverage: 0.0% of statements
	GophKeeper/pkg/customErrors		coverage: 0.0% of statements
	GophKeeper/pkg/store/postgresql		coverage: 0.0% of statements
	GophKeeper/pkg/store/sqllite		coverage: 0.0% of statements
	GophKeeper/pkg/store		coverage: 0.0% of statements
ok  	GophKeeper/pkg/logger	0.512s	coverage: 66.7% of statements
FAIL
```

2024-06-20 20:12 UTC, tmvrus commented
напоминаю на всякий случай
<img width="754" alt="image" src="https://github.com/vvv9912/GophKeeper/assets/554425/7fc81d73-2af1-43d6-9425-0d74fbf8837e">

2024-06-27 17:55 UTC, vvv9912 commented
GophKeeper/internal/Server/app          coverage: 0.0% of statements
ok      GophKeeper/internal/Server/authorization        0.004s  coverage: 76.2% of statements
ok      GophKeeper/internal/Server/config       0.004s  coverage: 100.0% of statements
ok      GophKeeper/internal/Server/handler      0.008s  coverage: 91.7% of statements
ok      GophKeeper/internal/Server/middleware   0.004s  coverage: 100.0% of statements
ok      GophKeeper/internal/Server/service      4.012s  coverage: 70.9% of statements
ok      GophKeeper/internal/Agent/Encrypt       0.006s  coverage: 81.2% of statements
ok      GophKeeper/internal/Agent/app   0.004s  coverage: 24.0% of statements
?       GophKeeper/internal/Agent/model [no test files]
        GophKeeper/internal/Agent/service/mocks         coverage: 0.0% of statements
ok      GophKeeper/internal/Agent/command       0.006s  coverage: 49.5% of statements
ok      GophKeeper/internal/Agent/config        0.005s  coverage: 100.0% of statements
ok      GophKeeper/internal/Agent/server        0.010s  coverage: 92.0% of statements
ok      GophKeeper/internal/Agent/service       0.315s  coverage: 79.7% of statements
command - из-за ф-ции auth, тк там больше половины - обработка сообщений из консоли (при вводе в консоль) не знаю пока как обрабатывать, в Server/service - из-за парсинга, не получается  обработать ParserContentRange, тк regexp.MustCompile(`bytes (\d+)-(\d+)/(\d+)`) автоматически проверяет на int. и потом  в таком выражении практически нет смысла 	rangeMin, err := strconv.Atoi(match[1]) с проверкой на  err, тк она выполняется в регулярке

2024-07-04 09:45 UTC, tmvrus commented
тесты сломаны
```
>go test ./...
?   	GophKeeper/cmd/Agent	[no test files]
?   	GophKeeper/cmd/Server	[no test files]
?   	GophKeeper/internal/Agent/model	[no test files]
?   	GophKeeper/internal/Agent/service/mocks	[no test files]
?   	GophKeeper/internal/Server/app	[no test files]
?   	GophKeeper/pkg/customErrors	[no test files]
?   	GophKeeper/pkg/store	[no test files]
?   	GophKeeper/pkg/store/postgresql	[no test files]
?   	GophKeeper/pkg/store/sqllite	[no test files]
--- FAIL: TestEncryptFile_OutputDirPermissionDenied (0.00s)
    encrypt_test.go:151: EncryptFile() error = mkdir /root: read-only file system, wantErr true
FAIL
FAIL	GophKeeper/internal/Agent/Encrypt	0.466s
ok  	GophKeeper/internal/Agent/app	(cached)
ok  	GophKeeper/internal/Agent/command	(cached)
ok  	GophKeeper/internal/Agent/config	(cached)
ok  	GophKeeper/internal/Agent/server	0.741s
ok  	GophKeeper/internal/Agent/service	1.358s
ok  	GophKeeper/internal/Server/authorization	(cached)
ok  	GophKeeper/internal/Server/config	(cached)
ok  	GophKeeper/internal/Server/handler	(cached)
ok  	GophKeeper/internal/Server/middleware	(cached)
--- FAIL: TestCreatePathIfNotExists_PermissionError (0.00s)
    data_test.go:171:
        	Error Trace:	/tmp/GophKeeper/internal/Server/service/data_test.go:171
        	Error:      	Should be true
        	Test:       	TestCreatePathIfNotExists_PermissionError
map[]
FAIL
FAIL	GophKeeper/internal/Server/service	4.774s
ok  	GophKeeper/pkg/ShaHash	(cached)
ok  	GophKeeper/pkg/logger	(cached)
FAIL
```

2024-07-08 13:40 UTC, tmvrus requested changes
есть вопросы

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +func (db *Database) updateDataWithMeta(ctx context.Context, tx *sql.Tx, data []byte, metaData []byte) (int64, error) {
где это используется?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +	//todo
?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +	// todo
?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +	query1 := "UPDATE users_data SET is_deleted=$1 WHERE user_data_id = $2 and user_id = $3"
`query1` это пример креотивного нейминга

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +		var isDeleted bool
а зачем выделять эти переменные если можно сразу сканировать в структуру?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +	//}
в рабочем проекте не должно быть закоменченного кода

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/command/data.go
> +		logger.Log.Error("CreateCredentials failed", zap.Error(err))
return потерял

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +		return customErrors.NewCustomError(nil, http.StatusNotFound, "data not found")
зачем на уровне базы данных нужно знать что-то про http статусы?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +	return nil
?

2024-07-08 13:40 UTC, tmvrus commented on pkg/store/postgresql/data.go
> +		err = handleTransaction(tx, err)
а дальше что с ошибкой происходит?

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/app/app.go
> +
тут надо определится - либо паника, либо ошибка
но лучше - ошибка
https://go.dev/wiki/CodeReviewComments#dont-panic

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/app/app.go
> +		panic(err)
https://go.dev/wiki/CodeReviewComments#dont-panic

2024-07-08 13:40 UTC, tmvrus commented on cmd/Server/main.go
> +	app.Run(ctx)
ошибка не обрабатывается

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/server.go
> +	httpServer *http.Server
кто использует это поле?

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/app/app.go
> +	return
лишний

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/data.go
> +		//}
в рабочем проекте такого быть не должно

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/data.go
> +	if data == nil || len(data) == 0 {
зачем проверять одно и тоже два раз? если data == nil то совершенно точно будет len(data) == 0

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/data.go
> +	return hash, err
зачем возвращать ошибку с результатом?

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/data.go
> +	ok, _ := s.StoreData.ChangeData(ctx, userId, userDataId, lastTimeUpdate)
а почему ошибка не обрабатывается никак?

2024-07-08 13:40 UTC, tmvrus commented on internal/Server/service/server.go
> +		case <-ctx.Done():
зачем делать select для одного кейса?

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/command/auth.go
> +			match, err := regexp.MatchString("^[a-zA-Z][a-zA-Z0-9]*$", Login)
регулярка компилится в цикле каждую итерацию, ее можно было вычислить один

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/command/auth.go
> +		Password = args[1]
тут можно сделать красивый reutrn и дальше обойтись без отступа

2024-07-08 13:40 UTC, tmvrus commented on internal/Agent/command/auth.go
> +			match, err = regexp.MatchString("^[a-zA-Z][a-zA-Z0-9]*$", Password)
опять регулярка в цикле

2024-07-08 14:51 UTC, vvv9912 commented on pkg/store/postgresql/postgresql.go
> +		var isDeleted bool
Это не удобно, когда в структуре есть указатель на время ( а указатель нужен чтобы отличать от дефолтного значения, других способов как отличать задано или нет оно не знаю )

2024-07-08 17:26 UTC, vvv9912 commented on internal/Server/service/data.go
> +	ok, _ := s.StoreData.ChangeData(ctx, userId, userDataId, lastTimeUpdate)
хочу возвращать строго true/false

2024-07-08 17:36 UTC, vvv9912 commented on internal/Server/service/data.go
> +	ok, _ := s.StoreData.ChangeData(ctx, userId, userDataId, lastTimeUpdate)
чтобы дальше подготовить ответ

2024-07-08 18:58 UTC, vvv9912 commented on internal/Server/service/data.go
> +	ok, _ := s.StoreData.ChangeData(ctx, userId, userDataId, lastTimeUpdate)
а логирование в s.StoreData.ChangeData уже имеется, поэтому и смысла обновлять не видел

2024-07-09 06:21 UTC, tmvrus commented on pkg/store/postgresql/postgresql.go
> +		var isDeleted bool
для времени есть метод IsZero(), можно смотреть на него.
но тут кроме времени много полей который можно сразу читать в структуру, код будет короче

2024-07-09 07:24 UTC, vvv9912 commented on pkg/store/postgresql/data.go
> +		err = handleTransaction(tx, err)
Странную логику завершения транзакции сделал, переделал

2024-07-09 07:41 UTC, vvv9912 commented on internal/Server/service/server.go
> +	httpServer *http.Server
Забыл, думал завершение сервера  отдельно делать

2024-07-09 07:44 UTC, vvv9912 commented on internal/Server/service/data.go
> +	if data == nil || len(data) == 0 {
Но data ещё может же быть пустой строкой []byte("")

2024-07-10 07:06 UTC, tmvrus approved these changes

2024-07-10 16:18 UTC, merged